plugins:
  solved_group_name_can_queue_solved:
    default: ""
    client: true
  solved_group_name_can_queue_unsolved:
    default: ""
    client: true
  solved_group_name_can_process_solved:
    default: ""
    client: true
  solved_group_name_can_process_unsolved:
    default: ""
    client: true